apiVersion: apps/v1
kind: Deployment
metadata:
  name: PreQuestion
  labels:
    app: PreQuestion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: PreQuestion
  template:
    metadata:
      labels:
        app: PreQuestion
    spec:
      containers:
        - name: PreQuestion
          image: username/PreQuestion:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5